### ISSUE TITLE
Is the controller override necessary

### ISSUE THREAD

**Issue by aliomattux** [magefan/module-catalog#3]
Forgive as this isn't necessarily an issue but more of a design question.

I noticed in your code you have a controller override for the product. If the current category is not set, it appears that you arbitrarily set a category as current_category in registry, and also potentially load a lot of categories depending on the product configuration. Is this code really necessary for this module?

The code that appears to fix the issue is by adding the cache key right?

**Comment by ihorvansach** [comment]
@aliomattux , thank you for your quest. This extension fix a few issues that you may have on Magento 2 catalog, you can check README.md
Event observer catalog_controller_product_init_after  exists to fix the breadcrumbs issue, if you don't need it - just disable.

**Comment by magefan** [comment]
@aliomattux , than
